/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patron1;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static patron1.interfaz.txt_estado;
import static patron1.interfaz.txt_id;
import static patron1.interfaz.txt_latitud;
import static patron1.interfaz.txt_longitud;
import static patron1.interfaz.txt_tipo;

public class Vista extends javax.swing.JFrame {

      DefaultTableModel modelo;

    
    public Vista() {
        initComponents();
    }
    
    
    private void mostrar() {        
        modelo = new DefaultTableModel();               
        ResultSet rs = Database.getTabla("select Nombre,Funcion,Sueldo_Bruto from nomina");
        modelo.setColumnIdentifiers(new Object[]{"Nombre", "Cargo", "Sueldo Bruto"});
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                modelo.addRow(new Object[]{rs.getString("Nombre"),rs.getString("Funcion"),rs.getString("Sueldo_Bruto")});
            }            
            // asigna el modelo a la tabla
            nomina.setModel(modelo);            
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_recibirID = new javax.swing.JTextField();
        txt_recibirTipo = new javax.swing.JTextField();
        txt_recibirEstado = new javax.swing.JTextField();
        txt_recibirLatitud = new javax.swing.JTextField();
        txt_recibirLongitud = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        nomina = new javax.swing.JTable();
        btn_conectar = new javax.swing.JButton();
        filtro_estrategico = new javax.swing.JComboBox<>();
        filtro_tactico = new javax.swing.JComboBox<>();
        filtro_operativo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_cargo = new javax.swing.JTextField();
        txt_sueldo = new javax.swing.JTextField();
        btn_estado = new java.awt.Button();
        txt_sueldo2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_comision = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        jLabel1.setText("ESTADO DE TAREA");

        jLabel2.setText("ID");

        jLabel3.setText("Tipo desastre");

        jLabel4.setText("Estado");

        jLabel5.setText("Latitud");

        jLabel6.setText("Longitud");

        nomina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        nomina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nominaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(nomina);

        btn_conectar.setText("Conectar");
        btn_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conectarActionPerformed(evt);
            }
        });

        filtro_estrategico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DIRECTORA DE PLANIFICACION Y DESARROLLO", "DIRECTORA DE RECURSOS HUMANOS", "DIRECTORA ADMINISTRATIVO Y FINANCIERO", "DIRECTOR DE TECNOLOGIA", "DIRECTOR TECNICO", "DIRECTOR DE OPERACIONES DEL 911", " " }));
        filtro_estrategico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtro_estrategicoItemStateChanged(evt);
            }
        });

        filtro_tactico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENCARGADO DE SISTEMA", "ENC. DE RECEPCION EMERGENCIAS DEL 9-1-1", "COORD. RECEPCION DE EMERGENCIAS", "COORDINADOR RECEPCION DE EMERGENCIAS", "SUPERVISOR DE RECEPCION", "SUPERVISOR LINEA DE RUIDO", "SUPERVISOR DESPACHO", "SUPERVISOR DESPACHO DE EMERGENCIAS", "SUPERVISOR DESPACHO EMERGENCIA", "COORDINADOR DE ENLACE", "ENCARGADO RADIOCOMUNICACION", "ENC. ELECTRICO", "ENCARGADO DIVISION SERVICIOS ELECTRICOS", "SUPERVISION DIVISION SERVICIOS ELECTRICOS", "ENC. ELECTRICO", "COORDINADORA DE DESPACHO", "COORDINADORA DE RELACIONES INTERNACIONALES", "COORDINADORA DE DESPACHO", "ENCARGADA DEPARTAMENTO JURIDICO", "ENCARGADO DPTO. PLANI Y GESTION DE PROYECTOS", "COORDINADORA DE CALIDAD", "ENC. DPTO. DESARROLLO ORGANIZACIONAL Y GESTION CALIDAD", "ENC. DPTO. DE RECLUTAMIENTO Y SELECCION", "ENCARGADA DPTO. FINACIERO", "ENCARGADO CONTROL Y MANT BIENES", "ENCARGADO DIVISION Y TRANSPORTACION", "ENC. UNIDAD DE COMPRAS", "SUPERVISOR SERVICIOS GENERALES", "ENC. DIVISION SERVICIOS GENERALES", "ENC. DIVISION SOPORTE A USUARIOS", "ADMINISTRADOR DE REDES Y SERVIDORES" }));
        filtro_tactico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtro_tacticoItemStateChanged(evt);
            }
        });

        filtro_operativo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASESORA DE COMUNICACIONES", "ASISTENTE ADMINISTRATIVA", "TECNICO DE PLANIFICACION", "GESTOR DE PROYECTOS", "MONITOR DE CALIDAD INTERNO", "MONITOR DE CALIDAD", "ANALISTA DESARROLLO ORGANIZACIONAL", "ANALISTA DE RECURSOS HUMANOS", "OFICIAL DE ENTRENAMIENTO", "ANALISTA NOMINAS", "CONTADORA", "ANALISTA DE PRESUPUESTO", "ASISTENTE ADMINISTRATIVA", "ANALISTA DE CONTROL DE BIENES", "TECNICO EN CONTROL DE BIENES", "TECNICO DE SUMINISTRO Y ALMACEN ", "ANALISTA DE COMPRAS", "AUXILIAR DE ALMACEN ", "CHOFER", "CONSERJE", "MANTENIMIENTO", "CONSEJERO", "TECNICO EN MANTENIMIENTO", "ANALISTA DE REDES Y SERVIDORES", "ANALISTA GIS", "ANALISTA TELEMATICO", "SOPORTE A USUARIO", "GESTOR DE PROYECTOS TIC", "ANALISTA DE SERVIDORES Y DATA CENTER", "ANALISTA DE REDES Y COMUNICACIONES", "ANALISTA SEGURIDAD TIC", "ANALISTA SEGURIDAD TECNOLOGIA", "ANALISTA BASE DE DATOS", "ANALISTA BASE SITUACIONAL", "ANALISTA DE SISTEMAS", "ANALISTA GEOLOCALIZACION", "ESTADISTICO", "ANALISTA DE DATOS", "OPERADOR DEL 911", "ANALISTA RADIOCOMUNICACION", "SOPORTE TECNICO DE RADIOCOMUNICACION", "SOPORTE RADIOCOMUNICACION", "TECNICO EN COMUNICACIONES", "ANALISTA VIDEO VIGILANCIA", "SOPORTE TECNICO VIDEO VIGILANCIA", "ELECTRICISTA", "ANALISTA ELECTRICO", "OFICIAL DE ENTRAMIENTO", "ASESORA DE COMUNICACIONES" }));
        filtro_operativo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtro_operativoItemStateChanged(evt);
            }
        });

        jLabel7.setText("Filtro Estratégico");

        jLabel8.setText("Filtro Táctico");

        jLabel9.setText("Filtro Operativo");

        jLabel10.setText("Nombre");

        jLabel11.setText("Cargo");

        jLabel12.setText("Sueldo");

        btn_estado.setBackground(new java.awt.Color(255, 0, 51));
        btn_estado.setLabel("En proceso o Inactiva");
        btn_estado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_estadoMouseClicked(evt);
            }
        });
        btn_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estadoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setText("Retribución por tarea realizada con éxito");

        jLabel14.setText("Sueldo");

        jLabel15.setText("Comisión 5%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_recibirEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_recibirTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_recibirLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_recibirLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_recibirID, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(filtro_operativo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(filtro_tactico, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(filtro_estrategico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel10))
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_cargo)
                                                    .addComponent(txt_sueldo)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))))
                                            .addComponent(btn_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addGap(34, 34, 34))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_sueldo2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(txt_comision))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(btn_conectar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_recibirID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_recibirTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_recibirEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_recibirLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_recibirLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_conectar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filtro_estrategico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(filtro_tactico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(filtro_operativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_sueldo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_comision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conectarActionPerformed
        mostrar();
        // conector();
    }//GEN-LAST:event_btn_conectarActionPerformed

    private void filtro_estrategicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtro_estrategicoItemStateChanged
       String query = filtro_estrategico.getSelectedItem().toString();
       TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel> (modelo);
       nomina.setRowSorter(tr);
       
       if(query != " "){
           tr.setRowFilter(RowFilter.regexFilter(query));
       }else{
           nomina.setRowSorter(tr);
       }
    }//GEN-LAST:event_filtro_estrategicoItemStateChanged

    private void filtro_tacticoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtro_tacticoItemStateChanged
        String query = filtro_tactico.getSelectedItem().toString();
       TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel> (modelo);
       nomina.setRowSorter(tr);
       
       if(query != " "){
           tr.setRowFilter(RowFilter.regexFilter(query));
       }else{
           nomina.setRowSorter(tr);
       }
    }//GEN-LAST:event_filtro_tacticoItemStateChanged

    private void filtro_operativoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtro_operativoItemStateChanged
        String query = filtro_operativo.getSelectedItem().toString();
       TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel> (modelo);
       nomina.setRowSorter(tr);
       
       if(query != " "){
           tr.setRowFilter(RowFilter.regexFilter(query));
       }else{
           nomina.setRowSorter(tr);
       }
    }//GEN-LAST:event_filtro_operativoItemStateChanged

    private void nominaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nominaMouseClicked
        int seleccion = nomina.rowAtPoint(evt.getPoint());
        txt_nombre.setText(String.valueOf(nomina.getValueAt(seleccion, 0)));
        txt_cargo.setText(String.valueOf(nomina.getValueAt(seleccion, 1)));
        txt_sueldo.setText(String.valueOf(nomina.getValueAt(seleccion, 2)));
    }//GEN-LAST:event_nominaMouseClicked

    private void btn_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_estadoActionPerformed

    private void btn_estadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_estadoMouseClicked
        btn_estado.setBackground(Color.GREEN);
        btn_estado.setLabel("TAREA TERMINADA");
        Vista.txt_sueldo2.setText(txt_sueldo.getText());
        
        
        double comis=0;
        comis = Double.parseDouble(txt_sueldo2.getText()) * (0.05);
        txt_comision.setText(String.valueOf(comis));
    }//GEN-LAST:event_btn_estadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_conectar;
    private java.awt.Button btn_estado;
    private javax.swing.JComboBox<String> filtro_estrategico;
    private javax.swing.JComboBox<String> filtro_operativo;
    private javax.swing.JComboBox<String> filtro_tactico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable nomina;
    private javax.swing.JTextField txt_cargo;
    private javax.swing.JTextField txt_comision;
    private javax.swing.JTextField txt_nombre;
    public static javax.swing.JTextField txt_recibirEstado;
    public static javax.swing.JTextField txt_recibirID;
    public static javax.swing.JTextField txt_recibirLatitud;
    public static javax.swing.JTextField txt_recibirLongitud;
    public static javax.swing.JTextField txt_recibirTipo;
    private javax.swing.JTextField txt_sueldo;
    private static javax.swing.JTextField txt_sueldo2;
    // End of variables declaration//GEN-END:variables
}
